"""update user fk

Revision ID: 868ac23f3400
Revises: 4b951d9762fb
Create Date: 2026-07-15 16:42:39.507590

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "868ac23f3400"
down_revision: Union[str, Sequence[str], None] = "4b951d9762fb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("service_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "user", "service", ["service_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="foreignkey")
    op.drop_column("user", "service_id")
    # ### end Alembic commands ###
